CREATE TABLE payment_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    order_number VARCHAR(80) NOT NULL,
    keycloak_user_id VARCHAR(100) NOT NULL,
    amount NUMERIC(14, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    provider VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL,
    payment_method VARCHAR(60) NOT NULL,
    payment_reference VARCHAR(120) NOT NULL,
    gateway_reference VARCHAR(120),
    gateway_payment_url VARCHAR(2000) NOT NULL,
    failure_reason VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    succeeded_at TIMESTAMP,
    failed_at TIMESTAMP,
    CONSTRAINT uk_payment_attempt_order_id UNIQUE (order_id),
    CONSTRAINT uk_payment_attempt_reference UNIQUE (payment_reference)
);

CREATE INDEX idx_payment_attempt_user ON payment_attempts (keycloak_user_id);
CREATE INDEX idx_payment_attempt_status ON payment_attempts (status);

CREATE TABLE payment_refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_attempt_id BIGINT NOT NULL,
    refund_reference VARCHAR(120) NOT NULL,
    amount NUMERIC(14, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(40) NOT NULL,
    reason VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    CONSTRAINT uk_payment_refund_reference UNIQUE (refund_reference),
    CONSTRAINT fk_payment_refund_attempt FOREIGN KEY (payment_attempt_id) REFERENCES payment_attempts(id)
);

CREATE INDEX idx_payment_refund_attempt ON payment_refunds (payment_attempt_id);
