CREATE TABLE stock_balances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    sku VARCHAR(80) NOT NULL,
    product_name VARCHAR(200),
    warehouse_code VARCHAR(60) NOT NULL,
    total_quantity INT NOT NULL,
    reserved_quantity INT NOT NULL,
    active BOOLEAN NOT NULL,
    version BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_stock_product_warehouse UNIQUE (product_id, warehouse_code)
);

CREATE TABLE stock_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_number VARCHAR(80) NOT NULL UNIQUE,
    order_id BIGINT UNIQUE,
    order_number VARCHAR(80),
    warehouse_code VARCHAR(60) NOT NULL,
    status VARCHAR(30) NOT NULL,
    failure_reason VARCHAR(1000),
    release_reason VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    released_at TIMESTAMP
);

CREATE TABLE stock_reservation_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT NOT NULL,
    stock_balance_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    sku VARCHAR(80) NOT NULL,
    warehouse_code VARCHAR(60) NOT NULL,
    quantity INT NOT NULL,
    CONSTRAINT fk_reservation_items_reservation FOREIGN KEY (reservation_id) REFERENCES stock_reservations (id) ON DELETE CASCADE,
    CONSTRAINT fk_reservation_items_stock FOREIGN KEY (stock_balance_id) REFERENCES stock_balances (id)
);

CREATE TABLE inventory_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_balance_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    sku VARCHAR(80) NOT NULL,
    warehouse_code VARCHAR(60) NOT NULL,
    movement_type VARCHAR(40) NOT NULL,
    quantity_change INT NOT NULL,
    total_quantity_after INT NOT NULL,
    reserved_quantity_after INT NOT NULL,
    available_quantity_after INT NOT NULL,
    reference_type VARCHAR(60),
    reference_id VARCHAR(120),
    reason VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_inventory_ledger_stock FOREIGN KEY (stock_balance_id) REFERENCES stock_balances (id)
);

CREATE INDEX idx_stock_product_id ON stock_balances(product_id);
CREATE INDEX idx_stock_warehouse_code ON stock_balances(warehouse_code);
CREATE INDEX idx_reservation_order_id ON stock_reservations(order_id);
CREATE INDEX idx_reservation_status ON stock_reservations(status);
CREATE INDEX idx_ledger_product_id ON inventory_ledger(product_id);
CREATE INDEX idx_ledger_stock_balance_id ON inventory_ledger(stock_balance_id);
CREATE INDEX idx_ledger_created_at ON inventory_ledger(created_at);
