CREATE TABLE shipments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_number VARCHAR(80) NOT NULL,
    order_id BIGINT NOT NULL,
    order_number VARCHAR(80) NOT NULL,
    keycloak_user_id VARCHAR(100) NOT NULL,
    status VARCHAR(40) NOT NULL,
    carrier VARCHAR(120) NOT NULL,
    tracking_number VARCHAR(120) NOT NULL,
    cancellation_reason VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    shipped_at TIMESTAMP,
    out_for_delivery_at TIMESTAMP,
    delivered_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    CONSTRAINT uk_shipment_order_id UNIQUE (order_id),
    CONSTRAINT uk_shipment_number UNIQUE (shipment_number),
    CONSTRAINT uk_shipment_tracking_number UNIQUE (tracking_number)
);

CREATE TABLE shipment_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT NOT NULL,
    status VARCHAR(40) NOT NULL,
    note VARCHAR(1000),
    occurred_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_status_history_shipment
        FOREIGN KEY (shipment_id) REFERENCES shipments(id) ON DELETE CASCADE
);

CREATE INDEX idx_shipments_user ON shipments(keycloak_user_id);
CREATE INDEX idx_shipments_status ON shipments(status);
CREATE INDEX idx_shipments_order_number ON shipments(order_number);
CREATE INDEX idx_status_history_shipment ON shipment_status_history(shipment_id);
CREATE INDEX idx_status_history_occurred_at ON shipment_status_history(occurred_at);
